CREATE TABLE IF NOT EXISTS deleted_marks_archive (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  original_mark_id INT DEFAULT NULL,
  teacher_id INT NOT NULL,
  assignment_id INT NOT NULL,
  student_id INT NOT NULL,
  score DECIMAL(5,2) DEFAULT NULL,
  status VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  term VARCHAR(20) NOT NULL,
  aoi_label VARCHAR(20) NOT NULL,
  original_created_at TIMESTAMP NULL DEFAULT NULL,
  original_updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_by_user_id INT DEFAULT NULL,
  deleted_by_role VARCHAR(20) NOT NULL DEFAULT 'system',
  delete_reason VARCHAR(255) DEFAULT NULL,
  source_action VARCHAR(100) DEFAULT NULL,
  restored_at TIMESTAMP NULL DEFAULT NULL,
  restored_by_user_id INT DEFAULT NULL,
  restored_by_role VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_deleted_marks_assignment (assignment_id),
  KEY idx_deleted_marks_student (student_id),
  KEY idx_deleted_marks_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS deleted_alevel_marks_archive (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  original_mark_id INT DEFAULT NULL,
  learner_id INT NOT NULL,
  assignment_id INT DEFAULT NULL,
  subject_id INT DEFAULT NULL,
  exam_id INT DEFAULT NULL,
  score DECIMAL(10,2) DEFAULT NULL,
  teacher_id INT DEFAULT NULL,
  term VARCHAR(50) NOT NULL,
  deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_by_user_id INT DEFAULT NULL,
  deleted_by_role VARCHAR(20) NOT NULL DEFAULT 'system',
  delete_reason VARCHAR(255) DEFAULT NULL,
  source_action VARCHAR(100) DEFAULT NULL,
  restored_at TIMESTAMP NULL DEFAULT NULL,
  restored_by_user_id INT DEFAULT NULL,
  restored_by_role VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_deleted_alevel_assignment (assignment_id),
  KEY idx_deleted_alevel_learner (learner_id),
  KEY idx_deleted_alevel_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
